In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ------------------ --------------------- 5.8/12.4 MB 29.8 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.4 MB 24.2 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 20.8 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import numpy as np


In [ ]:
arr= np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

every thing converting in u32

In [ ]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array genrating function


In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr2= np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

printing zeros

In [ ]:
ar0= np.zeros(6)
ar0

array([0., 0., 0., 0., 0., 0.])

to print ones

In [ ]:
arr3=np.ones((2,3))
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

linspace prints the range of equall distance betweeen the given range

In [ ]:
arr4= np.linspace(1,5,10)
arr4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**Random genration function**

normal range

In [ ]:
np.random.rand(10)

array([0.26236314, 0.952081  , 0.10386695, 0.63443756, 0.89544316,
       0.22588453, 0.01124765, 0.10571844, 0.47265417, 0.47604904])

standization range

In [ ]:
np.random.randn(10)

array([ 2.20551973,  0.26852247, -0.63752516, -1.17188066,  0.83578107,
        1.05338712,  1.93850436,  1.34646226,  0.15365493, -0.73452817])

gernate random integer

In [ ]:
np.random.randint(10,20,10)

array([19, 13, 13, 16, 12, 16, 15, 11, 16, 15])

# Array attributes:---

In [ ]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

**array methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

sum of the column axis =0

In [ ]:
np.sum(arr,axis=0)

array([12, 15, 18])

sum of the rows axis=1

In [ ]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

mean


In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

index of the maximum element

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

**Reshaping and resizing**

In [ ]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

change it into the 2d array(6 rows x 5 columns)

In [ ]:
arr= arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Array indexing and slicing

slicing a vector

In [2]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

printing a single element from the array

In [3]:
arr[6]

np.int64(17)

slicing the array

In [5]:
arr[1:6]

array([12, 13, 14, 15, 16])

slicing with the steps 2

In [6]:
arr[3::2]

array([14, 16, 18, 20])

Slicing and indexing of a martix

In [7]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

printing a row

In [8]:
arr[5]

array([26, 27, 28, 29, 30])

printing a single element

In [9]:
arr[0,0]

np.int64(1)

printing a particular rows columns

In [10]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [11]:
arr[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**Boolean Indexing**

In [14]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [15]:
bool_index= arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [16]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

**Array Operations**

arithmetic operations

In [2]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [3]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

<h2><b>Broadcasting</b></h2>

In [8]:
l=[10,20,30,40]
arr= np.array(l)

In [9]:
arr+10


array([20, 30, 40, 50])

<h2>Deep and Shallow copy </h2>

In [11]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice= a[:5]
slice=slice*10
slice

array([10, 20, 30, 40, 50])

In [13]:
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Deep copy

In [14]:
a
b=a

In [15]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
a


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

<h2><b> Matrix operations </b><h2>

In [7]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [8]:
A


array([[1, 2],
       [3, 4]])

In [9]:
B

array([[5, 6],
       [7, 8]])

dot function of matrix

In [10]:
A@B

array([[19, 22],
       [43, 50]])

Transpose a matrix

In [11]:
A.T

array([[1, 3],
       [2, 4]])